# Generated by Django 4.1 on 2022-08-26 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_myuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('currently', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('first_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('number_of_bids', models.IntegerField(default=0)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
                ('description', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.address')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
