# Generated by Django 4.1 on 2022-09-23 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visitors',
            field=models.ManyToManyField(related_name='visited_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
