# Generated by Django 4.1 on 2022-09-23 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0002_item_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recommended_to',
            field=models.ManyToManyField(related_name='recommended_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
