# Generated by Django 4.1 on 2022-08-28 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_myuser_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0003_bid_item_bids_alter_item_seller_bid_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('IN', 'Inactive'), ('RU', 'Running'), ('AC', 'Acquired')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_bids', to='auctions.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_items', to='base.address'),
        ),
        migrations.AlterField(
            model_name='item',
            name='bids',
            field=models.ManyToManyField(related_name='bidded_items', through='auctions.Bid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
