# Generated by Django 4.1 on 2022-09-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_item_buyer_item_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buyer_rating',
            field=models.IntegerField(default=0),
        ),
    ]
