# Generated by Django 4.1 on 2022-09-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_item_buyer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notify_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='notify_seller',
            field=models.BooleanField(default=False),
        ),
    ]
