# Generated by Django 4.1 on 2022-09-03 17:30

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=auctions.models.upload_to),
        ),
    ]
