# Generated by Django 4.1 on 2022-09-04 15:33

import auctions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_item_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=auctions.models.upload_to)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_images', to='auctions.item')),
            ],
        ),
    ]
