# Generated by Django 4.1 on 2022-09-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMessages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_on',
            new_name='date',
        ),
    ]
