# Generated by Django 4.0.6 on 2022-08-12 11:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('location', django.contrib.gis.db.models.fields.PointField(primary_key=True, serialize=False, srid=4326)),
            ],
        ),
    ]
