# Generated by Django 4.1 on 2022-09-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_myuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
